### ISSUE TITLE
Installer Malware False Positive?

### ISSUE THREAD

**Issue by AdamWMidsUK** [codemicro/ukvbeta#6]
<img width="784" alt="screeny" src="https://user-images.githubusercontent.com/41256675/43044417-523a64ea-8d9d-11e8-89fe-054198ba2727.png">

Above error is apparent when scanning the installer with McAfee LiveSafe. Probably a false positive, but McAfee is a popular brand and may cause alarm for users.

Version - Beta1.3.3
Regards

Adam

**Comment by codemicro** [comment]
VirusTotal shows McAfee as the only AV to detect it.
http://prntscr.com/k9hbs0

**Comment by codemicro** [comment]
Can you provide your version of McAfee and the engine version please, eg:
```
Product: McAfee Security Center 16.0
Engine: 3181.0
```

**Comment by AdamWMidsUK** [comment]
McAfee LiveSafe 16.0 Release 16.0 R13
Engine version: 3412.0

**Comment by codemicro** [comment]
Submitted to McAfee. Now we're waiting on them.

**Comment by martyp187** [comment]
This may be linked to the same false positive. But each release, when I run the installer, Windows Defender pops up this message. Although, my guess is due to code signing?

![2018-07-22 18_34_19-window](https://user-images.githubusercontent.com/3107058/43048354-5161bf78-8dde-11e8-8fb1-c36f4bf14d52.jpg)

**Comment by codemicro** [comment]
Smartscreen. Windows pops that up because it notices it hasn't really seen this program much on any computer running Windows and that is connected to the internet. It would help were it signed, but I'm looking into that. [Wikipedia article on it.](https://en.wikipedia.org/wiki/Microsoft_SmartScreen)

**Comment by codemicro** [comment]
Not sure if this will work or not, but could you try this?: [https://github.com/codemicro/ukvbeta/blob/master/installers/earlyaccess/FlyUK_GSX-setup_BETAv1.3.3sign.exe](https://github.com/codemicro/ukvbeta/blob/master/installers/earlyaccess/FlyUK_GSX-setup_BETAv1.3.3sign.exe). You can download it from that page.

**Comment by codemicro** [comment]
🤔 why is this not showing on the webhook?

**Comment by martyp187** [comment]
The same result with that installer. Same pop-up.

**Comment by codemicro** [comment]
That was more for Adam, to be honest! :P

**Comment by AdamWMidsUK** [comment]
Yes - the windows warning appears, but the False positive is gone from the link you sent!

**Comment by codemicro** [comment]
Brilliant. That either meants that McAfee did something, or me signing the installer helped.
